### ISSUE TITLE
Datenaktualisierung: Bilder von Artwork wegnehmen

### ISSUE THREAD

**Issue by ukeller** [particip-app/issues#71]
**Umgebung:**  Android generisch

**Version:** 7(1.0)
### Expected behaviour
- Gelöschte bzw. nicht referenzierte Bilder sind für den Benutzer nicht sichtbar
### Actual behaviour
- Bilder sind für den Benutzer noch sichtbar.
### Steps to reproduce
- Im Backend Bild b an Artwork a anfügen
- Android, Datensynchronisation
- Android, prüfen, dass Artwork a Bild b hat
- Im Backend Bild b von Artwork a wegnehmen
- Android, Datensynchronisation
- Android, prüfen, dass Artwork a Bild b nicht mehr hat

**Comment by ukeller** [comment]
Beispiel Datensatz "Weltpostdenkmal", Bild: Square 02_18_04 ist gelöscht und wird angezeigt (wurde gelöscht, um das Abstürzen der App bei dazugehörigen fehlendem Img (Vollformat) zu verhindern)

**Comment by ukeller** [comment]
Bitte prüfen.

**Comment by Kristinaherbst** [comment]
Das Problem besteht nachwievor. Jedoch ist es auch bei IOS so, dass man weder Bilder im Backend löschen oder hinzufügen kann. Ich habe das Prozedere am Objekt Weltpostdenkmal als auch bei Ueli Berger Chribbel durchgetestet - leider ohne Erfolg. Auch nach dem ich Datenaktualisierung geklickt hatte, ist die App nicht synchron mit den Bildern im Backend. @MichaelRoethlin 

Umgebung: Android generisch

Version:  1.0(11) auch IOS 

Expected behaviour

Gelöschte bzw. nicht referenzierte Bilder sind für den Benutzer nicht sichtbar

Actual behaviour

Bilder sind für den Benutzer noch sichtbar.
Steps to reproduce

Im Backend Bild b an Artwork a anfügen
Android, Datensynchronisation
Android, prüfen, dass Artwork a Bild b hat
Im Backend Bild b von Artwork a wegnehmen
Android, Datensynchronisation
Android, prüfen, dass Artwork a Bild b nicht mehr hat

**Comment by MichaelRoethlin** [comment]
Vorsicht: wenn Bilder zu einem Werk hinzugefügt resp. weggenommen werden, dürfen sie **nicht** nur versteckt werden (Glühlampe), sondern der Verweis muss gelöscht werden!!

Ich habe soeben bei Chribel ein 3. Bild in Typo3 als Referenz angefügt, das erschien nach der Synchronisation; ich habe es wieder im Typo3 weggelöscht, nach der Synchronisation war es auch in der App wieder weg.

Wichtig bei iOS ist, dass die Benennung der Bilder haargenau stimmt, gem. [Namenskonvention](https://github.com/particip-app/issues/blob/master/ImageFormats.md). Wenn z. B. 2x ein Bild mit Laufnummer `-01.jpg` eingefügt wird, wird dies nicht funktionieren, es braucht unterschiedliche (wenn auch bei iOS nicht nahtlos aufsteigende) Laufnummern!

@Kristinaherbst 
Was genau hast du bei Chribel erfolglos versucht?

**Comment by Kristinaherbst** [comment]
Ja es mag daran liegen, dass ich ein Bild gewählt habe, welches nicht die richtige Bezeichnung hat. Aber Bsp. "Weltpostdenkmal", die eine Abbildung im Square und Img ist so schlecht aufgelöst, dass ich sie gelöscht habe. Sie bleibt aber dennoch im App sichtbar. 
Bei Chribel habe ich versuchsweise ein Foto hinzugefügt, was die falsche Bezeichnung hatte- aber das habe ich bereits wieder gelöscht.

**Comment by MichaelRoethlin** [comment]
OK, ich glaube, ich sehe was passiert, die Verweise werden in der iOS-App nicht herausgelöscht, wenn sie mal drin sind, grr!

**Comment by ukeller** [comment]
Bei der Version 11(1.0) gab es folgende Einschränkungen:
- Die Uhrzeit des Telefons musste korrekt eingestellt sein
- Datensynchronisation war gedrosselt und nur alle 20 Sekunden möglich
  Diese Einschränkungen habe ich in der Version 12(1.0) entfernt.

@Kristinaherbst könntest du die Version 12(1.0) testen?

@MichaelRoethlin 
Auf dem Link unten ist ein Video, wie ich von Chribbel 1 Square wegnehme. In dem ich die Daten zwischen Android-Emulator und Service manipuliere. Die zugehörigen Scripts sowie das Excel sind ebenfalls dabei. Dabei muss im Emulator die Proxy-URL verwendet werden, statt des richtigen Service. Auf IOS-Emulator und Android-Emulator wäre das http://10.0.2.2:8888/service/apiv1/, auf Genymotion http://10.0.3.2:8888/service/apiv1/.

https://drive.google.com/folderview?id=0B3IjAQZHf_VTLUVEUE90VHFoczA&usp=sharing

**Comment by Kristinaherbst** [comment]
alles ok
